---
- hosts: tpi_cluster

  tasks:
    - name: Create cgroup memory boot config
      include_tasks: ./role/create_cgroup_memory.yml

    - name: Update and install apt packages
      include_tasks: ./role/apt.yml

    - name: Install K3s
      include_tasks: ./role/install_k3s.yml
