---
- name: Set cgroup string and path to cmdline.txt
  set_fact:
    cgroup_string: 'cgroup_enable=memory cgroup_memory=1'
    cmdline_path: '/boot/cmdline.txt'

- name: 'Search for cgroup phrase in cmdline.txt'
  ansible.builtin.shell: "grep -i '{{ cgroup_string }}' {{ cmdline_path }}"
  failed_when: false
  changed_when: false
  register: grep_output

- name: Assure cgroup memory is available
  when: grep_output.stdout_lines | length == 0
  ansible.builtin.lineinfile:
    path: '{{ cmdline_path }}'
    regexp: '^(console=.*)'
    backrefs: true
    line: '\1 cgroup_enable=memory cgroup_memory=1'
  register: lineinfile_output
  become: true

- name: Reboot
  when: lineinfile_output.changed
  ansible.builtin.reboot:
  become: true
